SELECT G3.ID AS ID
FROM ECOLI_DATA G3
JOIN (
    SELECT G2.ID
    FROM ECOLI_DATA G2
    JOIN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
        ) AS G1
    ON G2.PARENT_ID = G1.ID
    ) G2
ON G3.PARENT_ID = G2.ID
ORDER BY G3.ID;
