SELECT 
    ECOLI_DATA.ID AS ID,
    CASE
        WHEN A.RANKING <= A.TOTAL * 0.25 THEN 'CRITICAL'
        WHEN A.RANKING <= A.TOTAL * 0.5 THEN 'HIGH'
        WHEN A.RANKING <= A.TOTAL * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    ECOLI_DATA
JOIN
    (SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING, COUNT(*) OVER() AS TOTAL
    FROM ECOLI_DATA) AS A
ON
    ECOLI_DATA.ID = A.ID
ORDER BY ECOLI_DATA.ID;