WITH TOTAL2021 AS (
    SELECT COUNT(*) AS TOTAL_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
),
PURCHASE2021 AS (
    SELECT 
        YEAR(O.SALES_DATE) AS 'YEAR',
        MONTH(O.SALES_DATE) AS 'MONTH',
        COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO U
    JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
    WHERE YEAR(U.JOINED) = '2021'
    GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE) 
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND((PURCHASED_USERS / (SELECT TOTAL_COUNT FROM TOTAL2021)), 1) AS PUCHASED_RATIO
FROM PURCHASE2021
ORDER BY 1, 2;