WITH RECURSIVE GENERATION AS (
    SELECT ID, 1 AS G
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.G + 1 AS G
    FROM ECOLI_DATA CHILD
    JOIN GENERATION PARENT
    ON CHILD.PARENT_ID = PARENT.ID
)

SELECT COUNT(*) AS 'COUNT', G AS GENERATION
FROM GENERATION
WHERE NOT EXISTS (
    SELECT *
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = GENERATION.ID
)
GROUP BY G
ORDER BY G;