WITH CODES AS (SELECT CODE
FROM SKILLCODES
WHERE CATEGORY = 'Front End')

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN CODES C
ON D.SKILL_CODE & C.CODE = C.CODE
ORDER BY D.ID