WITH SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

    
SELECT S.YEAR, S.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID AS ID
FROM ECOLI_DATA E
JOIN SIZE S
ON YEAR(E.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY 1, 2