WITH MOST_VIEW AS (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT 
    CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('/home/grep/src/', U.BOARD_ID), '/'), U.FILE_ID), FILE_NAME), FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE U
WHERE U.BOARD_ID = (
    SELECT BOARD_ID FROM MOST_VIEW
)
ORDER BY FILE_ID DESC