WITH FRONTEND AS (
    SELECT SUM(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT CODE AS PY_CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
CSHARP AS (
    SELECT CODE AS CS_CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT
    CASE
        WHEN (D.SKILL_CODE & F.FE_CODE) > 0 AND (D.SKILL_CODE & P.PY_CODE) > 0 THEN 'A'
        WHEN (D.SKILL_CODE & C.CS_CODE) > 0 THEN 'B'
        WHEN (D.SKILL_CODE & F.FE_CODE) > 0 THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN FRONTEND F
JOIN PYTHON P
JOIN CSHARP C
GROUP BY GRADE, D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID;